name: Update IP List

on:
  schedule:
    - cron: '0 */8 * * *' # 每8小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS PERMISSIONS BLOCK
      contents: write # <--- ADD THIS LINE
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      run: python ${{ github.workspace }}/collect_ips.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "279469402@qq.com"
        git config --global user.name "lyl7410"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
